### ISSUE TITLE
stopped working (feb 2019)

### ISSUE THREAD

**Issue by CAH1983** [EmmanuelBeziat/vscode-great-icons#141] opened 2019-02-15 20:14 UTC
When I first installed it, (Jan 2019) it did work but now all the icons have disappeared. I use Mac OS Mojave 10.14.3 (18D109).

**Comment by EmmanuelBeziat** [comment] 2019-02-15 22:49
Hi,
There is no reason for it to suddenly stop showing icons. Maybe try reinstalling the icons set. If the problem remains, maybe another plugin you recently installed is preventing vscode to load icons?

**Comment by CAH1983** [comment] 2019-02-16 09:56
I uninstalled and reinstalled it but still the icons were not showing.

**Comment by EmmanuelBeziat** [comment] 2019-02-16 16:59
You might try to temporary disable all extensions but this one, and see if the problem remains.
https://github.com/Microsoft/vscode/issues/14992#issuecomment-258778708 

Let me know if anything changes

**Comment by mynameistechno** [comment] 2019-02-25 23:53
This stopped working for me as well after VS Code recent update. Looks like they redid their tree view:
https://code.visualstudio.com/updates/v1_31#_new-tree-widget could that have caused it?

**Comment by EmmanuelBeziat** [comment] 2019-02-27 09:38
Hi @mynameistechno, sorry to hear that you have this problem too :(

If the issue were to be caused by a specific change in the treeview, it would be a global issue for all users; and might impact other icons sets too.
But it's still working perfectly on my 2 Windows and my Mac, and for everybody else as far as I know…

Can you try this?

> You might try to temporary disable all extensions but this one, and see if the problem remains.
Microsoft/vscode#14992 (comment)
> Let me know if anything changes

Also, can you specify your setup (mac/windows)?
Thanks!

**Comment by EmmanuelBeziat** [comment] 2019-02-28 13:57
Hi @CAH1983, Hi @mynameistechno 

A new version of GreatIcons (2.1.47) has just been released, can you check if this new version solves your problem?

If not, you might still try to disable all extensions to see if it has any impact.

Thanks!

**Comment by CAH1983** [comment] 2019-02-28 14:26
OK, thank you for the update Emmanuel!

**Comment by mynameistechno** [comment] 2019-02-28 16:47
I uninstalled, reinstalled didn't work initially. But I forgot to reselect the font theme. After doing that, it's working again. Thanks! Can close this ticket from my end.

**Comment by EmmanuelBeziat** [comment] 2019-02-28 22:51
Okay @mynameistechno thanks
@CAH1983 , is it working for you?

**Comment by CAH1983** [comment] 2019-02-28 23:36
Yes. Thank you!

**Comment by EmmanuelBeziat** [comment] 2019-03-01 12:50
Nice, I close then :) Thanks to you both!

**Closed by EmmanuelBeziat** 2019-03-01 12:50 UTC
Labels: Solved ᕦ(ò_óˇ)ᕤ, bug (ʘ言ʘ╬)
